server:
  port: 7012
  servlet:
    contextPath: /playandgo

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URL:}
      auto-index-creation: true
  http:
    multipart:
      enabled: true
      max-file-size: ${SPRING_HTTP_MULTIPART_MAX_FILE_SIZE:}
      max-request-size: ${SPRING_HTTP_MULTIPART_MAX_REQUEST_SIZE:}

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: ${AAC_ISSUER_URI:}
        client-id: ${AAC_CLIENT_ID:}
      opaque-token:
        introspection-uri: 
        client-id: 
        client-secret: 

mail:
  host: ${MAIL_HOST:}
  port: ${MAIL_PORT:}
  user: ${MAIL_USER:}
  password: ${MAIL_PASSWORD:}
  from: ${MAIL_FROM:}
  url: ${MAIL_URL:}

gamification:
  url: ${GAMIFICATION_URL:}
  secretKey: ${GAMIFICATION_SECRETKEY:}
  user: ${GAMIFICATION_USER:}
  password: ${GAMIFICATION_PASSWORD:}

rabbitmq_pg:
  host: ${RABBITMQ_PG_HOST:}
  port: ${RABBITMQ_PG_PORT:}
  user: ${RABBITMQ_PG_USER:}
  password: ${RABBITMQ_PG_PASSWORD:}
  virtualhost: ${RABBITMQ_PG_VIRTUALHOST:}

rabbitmq_ge:
  host: ${RABBITMQ_GE_HOST:}
  port: ${RABBITMQ_GE_PORT:}
  user: ${RABBITMQ_GE_USER:}
  password: ${RABBITMQ_GE_PASSWORD:}
  virtualhost: ${RABBITMQ_GE_VIRTUALHOST:}
  geExchangeName: ${RABBITMQ_GE_EXCHANGE_NAME:}
  geRoutingKeyPrefix: ${RABBITMQ_GE_ROUTING_KEY_PREFIX:}

validation:
  shapefolder: ${VALIDATION_SHAPE:}

notificationDir: ${NOTIFICATION_DIR:}

gcm:
  gcmSenderApiKey: ${GCM_SENDER_API_KEY:}
  gcmSenderId: ${GCM_SENDER_ID:}  